language: python
python:
  - "3.4"
  - "3.6"
install:
  - pip install -r requirements.txt
  - pip install coverage codecov
script:
  - coverage run tests/ghuserTester.py
after_success:
  - codecov --token=$COVERAGE
